name       : libvsqlite++
version    : 0.3.13
release    : 2
source     :
    - https://github.com/vinzenz/vsqlite--/archive/0.3.13.tar.gz : 73dea3c0b4b7769254da17182efbf9fc16893c50ed0d544abfdde127b69467d5
license    : BSD-3-Clause
component  : programming.development
summary    : A well designed and portable SQLite3 Wrapper for C++.
description: |
    A well designed and portable SQLite3 Wrapper for C++.
builddeps  :
    - pkgconfig(sqlite3)
    - libboost-devel
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
