name       : libvsqlite++
version    : 0.3.13
release    : 1
source     :
    - https://evilissimo.fedorapeople.org/releases/vsqlite--/0.3.13/vsqlite++-0.3.13.tar.gz : 67887fe7e27159fc83de271a015c322d40bb760f1a7ac5ae9c1d40291a90d39d
license    : BSD-3-Clause
component  : programming.development
summary    : A well designed and portable SQLite3 Wrapper for C++.
description: |
    A well designed and portable SQLite3 Wrapper for C++.
builddeps  :
    - pkgconfig(sqlite3)
    - libboost-devel
setup: |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
